// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu9Kv5RFZgUw8Yw56uyFwFV2yy6mEr7qs',
    appId: '1:731928927455:web:2650945336c2ca806edd6a',
    messagingSenderId: '731928927455',
    projectId: 'kvappka',
    authDomain: 'kvappka.firebaseapp.com',
    databaseURL: 'https://kvappka-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kvappka.appspot.com',
    measurementId: 'G-9566EC2LTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6877PnFeKEAZtn7P8Y-MuBeR_7NPZxJc',
    appId: '1:731928927455:android:a36ab1e2429bc84f6edd6a',
    messagingSenderId: '731928927455',
    projectId: 'kvappka',
    databaseURL: 'https://kvappka-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kvappka.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA22uPXKkWWS4YrM0zBiF-_fE2LAqPUlvc',
    appId: '1:731928927455:ios:6ad5c27036bf8e446edd6a',
    messagingSenderId: '731928927455',
    projectId: 'kvappka',
    databaseURL: 'https://kvappka-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kvappka.appspot.com',
    iosClientId: '731928927455-th7su0k8qmupt4jt6uarilcrj6srt43n.apps.googleusercontent.com',
    iosBundleId: 'com.darkfox.kvappka',
  );
}
